### ISSUE TITLE
error with version 0.13 that forces windows to restart

### ISSUE THREAD

**Issue by DessertArbiter** [FailedShack/USBHelperLauncher#29]
whenever i launch it with version 0.13 i get some errors about the 3ds titlekeys website not working and then windows says it has an error and restarts. it also caused chrome to reset itself back to default. i reverted back to 0.12b and it works fine

**Comment by FailedShack** [comment]
This doesn't seem like an issue related to USBHelperLauncher.
What error does Windows show? A BSOD?
However the weirdest part is Chrome resetting its settings to default.

No new features were added between 0.12b and 0.13 that could remotely interfere with either of these things, the changes were mostly inter-process communication improvements and other bugfixes.
I would need to be able to reproduce your issue to be able to fix it. However, it seems likely that this could have been caused by something else. Would you mind updating to 0.13 to try again?
It would also be helpful to know more information about your system (specs, os, .NET version...).

**Comment by DessertArbiter** [comment]
I added it to my antivirus exclusions and now it works, i guess something in 0.13 causes problems with avast
