### ISSUE TITLE
Not all games appearing?

### ISSUE THREAD

**Issue by Madridi7** [FailedShack/USBHelperLauncher#31]
I am not sure if this is related to this or not. But once I was able to use this to get usbhelper running again, I wanted to download Just dance 2019.

To my surprise, the game was not there? Even though its on the title key site,

So is this issue has to do with the patching process that the launcher does? or is there something wrong with the program itself? Or am I missing something?

Thanks

**Comment by Pythonic-Rainbow** [comment]
I can no longer search Mario Kart 8 either

**Comment by FailedShack** [comment]
This is because [games.json](https://github.com/FailedShack/USBHelperLauncher/blob/master/USBHelperLauncher/data/games.json) is not up to date. I'll have to regenerate the database files soon, in the meantime you can just add Just Dance 2019 manually.

Make sure your title key site is up to date and paste the following before the closing square bracket at the end of games.json:
`{"EshopId":"20010000028068","IconUrl":"https://kanzashi-wup.cdn.nintendo.net/i/2b8ed1b74826e52dcab4bd6a1650f34be273621a02072fa034ccd2abc0681d66.jpg","Name":"Just Dance® 2019","Platform":125,"ProductCode":"HJDE","Region":"USA","Size":"16129295736","TitleId":"0005000010217300","PreLoad":false,"Version":"","DiscOnly":false}`
Restart Wii U USB Helper and the US release of Just Dance 2019 should appear.

@Pythonic-Rainbow Your issue sounds like your title key site is not properly configured, make sure to follow each step of the Reddit guide closely. I would suggest a clean install.
